export const EXPERIENCE_TITLE = '17 años de experiencia en pos de tu proyecto';
export const EXPERIENCE_DESCRIPTION = `Especializados desde 1996 en usabilidad, experiencia del usuario (UX) y diseño de experiencias de proyectos digitales. Aportamos estrategia e innovación centrada en el usuario y los objetivos de negocio de tu proyecto. Cotrabajando mejoraremos tu tasa de conversiòn, KPI's, ROI y los resultados de tu actual publicidad PPC (pay per click).`;
export const PROJECTS_TITLE = 'Proyectos destacados';
export const PROJECTS_DESCTIPTION = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus';
export const CLIENTS_TITLE = 'Lo que dicen nuestros clientes';
export const CLIENTS_DESCTIPTION = '';
export const LETS_TALK_BUTTON = 'Hablemos de tu proyecto';
export const SPECIALIZE_DESCTIPTION = 'Nos especializamos en';
export const SPECIALIZE_TEXT = 'interfaces digitales que los usuarios aman';
